### ISSUE TITLE
How to add tag SupplierAssignedAccountID

### ISSUE THREAD

**Issue by jw7712** [uctoplus/ubl-wrapper#3]
I'm trying to export UBL invoices for importing in an accounting application (Venice) and need to add cac:AccountingCustomerParty/cbc:SupplierAssignedAccountID to the XML file.

How can this be done using this package?

Thanks in advance
![Screenshot from 2022-12-05 15-18-22](https://user-images.githubusercontent.com/57006726/205935672-b301fca7-47cb-439d-9b78-3ba182b3e864.png)

**Comment by MimoGraphix** [comment]
Hi, according to DOCs http://www.datypic.com/sc/ubl21/e-cac_AccountingCustomerParty.html this model is used in the list of models. Are you using one of them? If yes there should already be defined getter and setter for this type.

cac:AccountinCustomerParty is type of CustomerPartyType.
