### ISSUE TITLE
Extension and Signature components

### ISSUE THREAD

**Issue by potatocode420** [uctoplus/ubl-wrapper#4]
Hey there, is this repo still being maintained? I notice it still lacks the following extension and component signatures:
http://www.datypic.com/sc/ubl21/s-UBL-CommonExtensionComponents-2.1.xsd.html
http://www.datypic.com/sc/ubl21/s-UBL-CommonSignatureComponents-2.1.xsd.html

**Comment by uctoplus** [comment]
Hi, yes this repo is maintained but we are currently not planning to implement this parts. But feel free to make a pull request, we will be very happy if this repo got better with your contribution.
